name: interviewo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  
  
  fluttertoast: ^8.1.2
  flutter_bloc: ^8.1.1
  
  salomon_bottom_bar: ^3.3.1
  getwidget: ^3.0.1
  hexcolor: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_onboarding_slider: ^1.0.8
  video_player: ^2.6.0
  appinio_video_player: ^1.2.0
  get: 
  flutter_zoom_drawer: ^3.0.4+1
  line_awesome_flutter: ^2.0.0
  sliding_clipped_nav_bar: ^3.1.0+4
  bottom_navy_bar: ^6.0.0
  floating_bottom_navigation_bar: ^1.5.2
  
  flutter_material_pickers:
  adaptive_theme: ^3.2.0 
  file_picker:  
  numberpicker: ^2.1.2
  chips_choice: ^3.0.0
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  hive: ^2.2.3



  # firebase plugins
  firebase_core:
  firebase_messaging: ^14.1.3
  firebase_analytics: ^10.0.6
  firebase_dynamic_links: ^5.0.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  image_picker: ^0.8.7+3
  stacked: ^3.2.0
  path: ^1.8.3
  path_provider: ^2.0.14
   
  stylish_bottom_bar: ^1.0.0
  shaky_animated_listview: ^0.0.5
  curved_drawer_fork: ^0.0.1+1
  
  string_validator: ^1.0.0
  
  

  #service plugins
  connectivity_wrapper: ^1.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  device_info_plus:  ^3.2.4
  package_info_plus: any
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - json/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/montserrat_bold.ttf                                                                               
  #       - asset: assets/fonts/montserrat_regular.ttf
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages